# Generated by Django 5.0.7 on 2024-07-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SndMessage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
