# Generated by Django 5.0.7 on 2024-07-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SndMessage', '0002_rename_settings_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=False)),
            ],
        ),
    ]
